use rusty_rival::fen::{get_position, get_supplement};
use rusty_rival::moves::allocate_magic_boxes;
use rusty_rival::perft::perft;

#[test]
fn it_returns_the_total_number_of_moves_in_a_full_move_tree_of_a_given_depth_with_a_given_position_as_its_head() {
    let magic_box = &allocate_magic_boxes();

    let mut position = get_position(&"8/p7/8/1P6/K1k3pP/6P1/8/8 b - h3 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 8);
    let mut position = get_position(&"5k2/5p1p/p3B1p1/P5P1/3K1P1P/8/8/8 b - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 9);
    let mut position = get_position(&"8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 14);
    let mut position = get_position(&"rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 20);
    let mut position = get_position(&"rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 20);

    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/R3K2R w KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 17);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/R3KR2 b Qkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 17);
    let mut position = get_position(&"r3k2r/p6p/8/8/1Bp1p3/3b4/P6P/R3K2R b KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 19);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/R3K1R1 b Qkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 19);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/1R2K2R b Kkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 20);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/2R1K2R b Kkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 20);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/3RK2R b Kkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 20);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P4K1P/R6R b kq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 20);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p2P/3b4/P7/R3K2R b KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 20);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b3P/P7/R3K2R b KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 20);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P2K3P/R6R b kq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 20);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/R2K3R b kq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 20);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/2KR3R b kq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 20);
    let mut position = get_position(&"r3k2r/p6p/8/B7/Ppp1p3/3b4/7P/R3K2R b KQkq a3 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 21);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/P2b4/7P/R3K2R b KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 21);
    let mut position = get_position(&"r3k2r/p1B4p/8/8/1pp1p3/3b4/P6P/R3K2R b KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 21);
    let mut position = get_position(&"r2Bk2r/p6p/8/8/1pp1p3/3b4/P6P/R3K2R b KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 21);
    let mut position = get_position(&"r3k2r/p6p/1B6/8/1pp1p3/3b4/P6P/R3K2R b KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 22);

    let mut position = get_position(&"rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 400);

    let mut position = get_position(&"8/p7/8/1P6/K1k3pP/6P1/8/8 b - h3 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 8);
    let mut position = get_position(&"8/p7/8/1P6/K1k5/6Pp/8/8 w - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 4);
    let mut position = get_position(&"8/8/p7/1P6/K1k3pP/6P1/8/8 w - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 5);
    let mut position = get_position(&"8/p7/8/1Pk5/K5pP/6P1/8/8 w - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 5);
    let mut position = get_position(&"8/p7/8/1P1k4/K5pP/6P1/8/8 w - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 6);
    let mut position = get_position(&"8/p7/8/1P6/K2k2pP/6P1/8/8 w - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 6);
    let mut position = get_position(&"8/p7/8/1P6/K5pP/2k3P1/8/8 w - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 4);
    let mut position = get_position(&"8/p7/8/1P6/K5pP/3k2P1/8/8 w - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 6);
    let mut position = get_position(&"8/8/8/pP6/K1k3pP/6P1/8/8 w - a6 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 5);
    let mut position = get_position(&"8/p7/8/1P6/K1k3pP/6P1/8/8 b - h3 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 41);

    let mut position = get_position(&"8/8/8/KP6/5pPk/8/4P3/8 b - g3 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 46);
    let mut position = get_position(&"r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 48);
    let mut position = get_position(&"8/2p5/8/KP6/5pPk/8/4P3/8 b - g3 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 57);
    let mut position = get_position(&"8/2p5/3p4/KP6/5pPk/8/4P3/8 b - g3 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 64);
    let mut position = get_position(&"4k3/8/8/8/8/8/PPPPPPPP/RNBQKBNR w KQ - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 100);
    let mut position = get_position(&"5k2/5p1p/p3B1p1/P5P1/3K1P1P/8/8/8 b - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 169);
    let mut position = get_position(&"8/2p5/3p4/KP5r/1R2Pp1k/8/6P1/8 b - e3 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 177);
    let mut position = get_position(&"8/8/3p4/KPp4r/1R3p1k/4P3/6P1/8 w - c6 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 190);
    let mut position = get_position(&"8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 191);
    let mut position = get_position(&"8/2p5/3p4/KP5r/R4p1k/8/4P1P1/8 b - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 202);
    let mut position = get_position(&"8/2p5/3p4/1P5r/KR3p1k/8/4P1P1/8 b - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 224);
    let mut position = get_position(&"8/2p5/3p4/KP5r/1R3pPk/8/4P3/8 b - g3 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 226);
    let mut position = get_position(&"8/2p5/K2p4/1P5r/1R3p1k/8/4P1P1/8 b - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 240);
    let mut position = get_position(&"8/3K4/2p5/p2b2r1/5k2/8/8/1q6 b - - 1 67".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 279);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/R2K3R b kq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 300);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/1R2K2R b Kkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 377);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/3RK2R b Kkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 365);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b3P/P7/R3K2R b KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 339);
    let mut position = get_position(&"r3k2r/p6p/8/B7/Ppp1p3/3b4/7P/R3K2R b KQkq a3 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 357);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p2P/3b4/P7/R3K2R b KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 358);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/P2b4/7P/R3K2R b KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 376);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/2R1K2R b Kkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 380);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/2KR3R b kq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 385);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/R3KR2 b Qkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 395);
    let mut position = get_position(&"r3k2r/p6p/8/8/1Bp1p3/3b4/P6P/R3K2R b KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 395);
    let mut position = get_position(&"r2Bk2r/p6p/8/8/1pp1p3/3b4/P6P/R3K2R b KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 403);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P4K1P/R6R b kq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 437);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P2K3P/R6R b kq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 437);
    let mut position = get_position(&"r3k2r/p1B4p/8/8/1pp1p3/3b4/P6P/R3K2R b KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 438);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/R3K1R1 b Qkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 454);
    let mut position = get_position(&"r3k2r/p6p/1B6/8/1pp1p3/3b4/P6P/R3K2R b KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 470);
    let mut position = get_position(&"r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 2039);
    let mut position = get_position(&"8/2p5/3p4/KP5r/1R3pPk/8/4P3/8 b - g3 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 2, &mut supplement, magic_box), 3702);
    let mut position = get_position(&"8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 2, &mut supplement, magic_box), 2812);

    let mut position = get_position(&"8/p7/8/1P6/K1k3pP/6P1/8/8 b - h3 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 2, &mut supplement, magic_box), 325);
    let mut position = get_position(&"8/p7/8/1P6/K1k3pP/6P1/8/8 b - h3 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 3, &mut supplement, magic_box), 2002);
    let mut position = get_position(&"8/p7/8/1P6/K1k3pP/6P1/8/8 b - h3 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 4, &mut supplement, magic_box), 16763);
    let mut position = get_position(&"8/p7/8/1P6/K1k3pP/6P1/8/8 b - h3 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 5, &mut supplement, magic_box), 118853);
    let mut position = get_position(&"8/p7/8/1P6/K1k3p1/6P1/7P/8 w - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 0, &mut supplement, magic_box), 5);
    let mut position = get_position(&"8/p7/8/1P6/K1k3p1/6P1/7P/8 w - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 39);
    let mut position = get_position(&"8/p7/8/1P6/K1k3p1/6P1/7P/8 w - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 2, &mut supplement, magic_box), 237);
    let mut position = get_position(&"8/p7/8/1P6/K1k3p1/6P1/7P/8 w - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 3, &mut supplement, magic_box), 2002);
    let mut position = get_position(&"8/p7/8/1P6/K1k3p1/6P1/7P/8 w - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 4, &mut supplement, magic_box), 14062);
    let mut position = get_position(&"8/p7/8/1P6/K1k3p1/6P1/7P/8 w - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 5, &mut supplement, magic_box), 120995);

    let mut position = get_position(&"5k2/5p1p/p3B1p1/P5P1/3K1P1P/8/8/8 b - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 3, &mut supplement, magic_box), 20541);
    let mut position = get_position(&"8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 3, &mut supplement, magic_box), 43238);
    let mut position = get_position(&"n1n5/PPPk4/8/8/8/8/4Kppp/5N1N b - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 3, &mut supplement, magic_box), 182838);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/1R2K2R b Kkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 3, &mut supplement, magic_box), 175927);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/2R1K2R b Kkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 3, &mut supplement, magic_box), 178248);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/3RK2R b Kkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 3, &mut supplement, magic_box), 168357);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P4K1P/R6R b kq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 3, &mut supplement, magic_box), 221267);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P2K3P/R6R b kq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 3, &mut supplement, magic_box), 213344);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/R2K3R b kq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 3, &mut supplement, magic_box), 120873);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/2KR3R b kq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 3, &mut supplement, magic_box), 184127);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/R3K1R1 b Qkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 3, &mut supplement, magic_box), 240619);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/R3KR2 b Qkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 3, &mut supplement, magic_box), 189825);
    let mut position = get_position(&"r3k2r/p6p/8/B7/Ppp1p3/3b4/7P/R3K2R b KQkq a3 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 3, &mut supplement, magic_box), 154828);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/P2b4/7P/R3K2R b KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 3, &mut supplement, magic_box), 173400);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p2P/3b4/P7/R3K2R b KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 3, &mut supplement, magic_box), 165129);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b3P/P7/R3K2R b KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 3, &mut supplement, magic_box), 151137);
    let mut position = get_position(&"r3k2r/p6p/1B6/8/1pp1p3/3b4/P6P/R3K2R b KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 3, &mut supplement, magic_box), 249845);
    let mut position = get_position(&"r3k2r/p1B4p/8/8/1pp1p3/3b4/P6P/R3K2R b KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 3, &mut supplement, magic_box), 227059);
    let mut position = get_position(&"r2Bk2r/p6p/8/8/1pp1p3/3b4/P6P/R3K2R b KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 3, &mut supplement, magic_box), 185525);
    let mut position = get_position(&"r3k2r/p6p/8/8/1Bp1p3/3b4/P6P/R3K2R b KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 3, &mut supplement, magic_box), 186968);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/R3K2R w KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 1, &mut supplement, magic_box), 341);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/R3K2R w KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 2, &mut supplement, magic_box), 6666);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/R3K2R w KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 3, &mut supplement, magic_box), 150072);

    let mut position = get_position(&"r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 2, &mut supplement, magic_box), 97862);
    let mut position = get_position(&"8/p7/8/1P6/K1k3pP/6P1/8/8 b - h3 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 6, &mut supplement, magic_box), 986637);
    let mut position = get_position(&"8/p7/8/1P6/K1k3p1/6P1/7P/8 w - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 6, &mut supplement, magic_box), 966152);
    let mut position = get_position(&"8/p7/8/1P6/K1k3p1/6P1/7P/8 w - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 7, &mut supplement, magic_box), 8103790);
    let mut position = get_position(&"8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 4, &mut supplement, magic_box), 674624);
    let mut position = get_position(&"r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 3, &mut supplement, magic_box), 4085603);
    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/2KR3R b kq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 4, &mut supplement, magic_box), 4238116);
    let mut position = get_position(&"rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 4, &mut supplement, magic_box), 4865609);

    let mut position = get_position(&"r3k2r/p6p/8/B7/1pp1p3/3b4/P6P/R3K2R w KQkq - 0 1".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 4, &mut supplement, magic_box), 3186478);
    let mut position = get_position(&"rnbqkb1r/ppppp1pp/7n/4Pp2/8/8/PPPP1PPP/RNBQKBNR w KQkq f6 0 3".to_string());
    let mut supplement = get_supplement(position.clone());
    assert_eq!(perft(&mut position, 4, &mut supplement, magic_box), 11139762);

}