#!/bin/bash

cargo clippy -- -Dwarnings
result=$?

if [[ ${result} -ne 0 ]] ; then
    cat <<\EOF
There are some Clippy issues, run `cargo clippy` first.
EOF
    exit 1
fi

diff=$(cargo fmt -- --check)
result=$?

if [[ ${result} -ne 0 ]] ; then
    cat <<\EOF
There are some code style issues, run `cargo fmt` first.
EOF
    exit 1
fi

exit 0

